version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:3000"
    volumes:
      # Mount the source code for hot reloading
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_INTERVAL=400
      - WATCHPACK_POLLING_INTERVAL=400
    stdin_open: true
    tty: true
    restart: unless-stopped
